refactor: events to structs
galacticcouncil/Basilisk-node pull request #459
Opened 2022-05-24 09:50 UTC by Roznovjak

Fixes: #326

2022-06-03 13:26 UTC, lumir-mrkva requested changes

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/duster/src/lib.rs
> +			account_id: T::AccountId,
account_id -> who

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/lbp/src/lib.rs
> +			pool_account_id: PoolId<T>,
pool_account_id -> id
pool_data -> data

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/marketplace/src/lib.rs
> +				owner: sender,
who

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/marketplace/src/lib.rs
> +				offerer: sender,
who

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/marketplace/src/lib.rs
> +				price: amount,
price -> amount

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/marketplace/src/lib.rs
> +			class_id: T::NftClassId,
class

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/marketplace/src/lib.rs
> +			instance_id: T::NftInstanceId,
instance

2022-06-03 13:26 UTC, lumir-mrkva commented on pallets/xyk/src/lib.rs
> +			pool_account_id: T::AccountId,
pool

2022-06-13 11:51 UTC, enthusiastmartin approved these changes
Let's sort out the versions and it is ready for merge .

2022-06-13 18:50 UTC, merged