feat/remove sudo
galacticcouncil/Basilisk-node pull request #515
Opened 2022-07-11 10:16 UTC by martinfridrich

Sudo pallet was removed from basilisk runtime.

2022-07-14 10:33 UTC, lumir-mrkva requested changes
we should shift some configuration tasks to the technical comitee majority

2022-07-14 15:09 UTC, martinfridrich commented
> we should shift some configuration tasks to the technical comitee majority

Which one? Most of the pallets are already configured `...TechCommitteeOrRoot`.

2022-07-14 15:43 UTC, lumir-mrkva commented
> > we should shift some configuration tasks to the technical comitee majority
> 
> Which one? Most of the pallets are already configured `...TechCommitteeOrRoot`.

ok, i'll review

2022-07-15 20:38 UTC, lumir-mrkva approved these changes

2022-07-15 21:18 UTC, lumir-mrkva commented on runtime/basilisk/src/xcm.rs
> +	type ControllerOrigin = MajorityTechCommitteeOrRoot;
yes, these roles are more for sorting out technical issues

2022-07-15 21:19 UTC, lumir-mrkva commented on runtime/basilisk/src/lib.rs
> +	type UpdateOrigin = MajorityTechCommitteeOrRoot;
yes, currently required to maintain stable running chain

2022-07-15 21:21 UTC, merged