feat: add transaction-pause pallet to testing runtime
galacticcouncil/Basilisk-node pull request #537
Opened 2022-07-29 12:33 UTC by Roznovjak

2022-08-05 09:13 UTC, lumir-mrkva requested changes
fix clippy & bump versions please

2022-08-08 20:07 UTC, lumir-mrkva commented
Task linked: [CU-2p79vzj Add tx-pause-pallet to testing runtime](https://app.clickup.com/t/2p79vzj)

2022-08-30 06:59 UTC, martinfridrich approved these changes

2022-09-02 13:21 UTC, lumir-mrkva approved these changes

2022-09-02 13:22 UTC, merged