feat: remove price-oracle pallet from testing runtime
galacticcouncil/Basilisk-node pull request #538
Opened 2022-07-29 12:58 UTC by Roznovjak

2022-08-05 09:14 UTC, lumir-mrkva requested changes
fix build & bump versions

2022-08-08 20:09 UTC, lumir-mrkva commented
Task linked: [CU-2p79w42 Remove price-oracle-pallet from testing runtime](https://app.clickup.com/t/2p79w42)

2022-08-24 06:22 UTC, martinfridrich approved these changes

2022-09-02 13:20 UTC, lumir-mrkva approved these changes

2022-09-02 13:20 UTC, merged