feat: state trie migration
galacticcouncil/Basilisk-node pull request #654
Opened 2024-01-29 12:43 UTC by Roznovjak

This PR integrates the state trie migration pallet and sets the state version of the runtime to 1. This change enables lazy storage migration.

2024-01-30 10:20 UTC, mrq1911 requested changes

2024-01-30 10:20 UTC, mrq1911 commented on runtime/basilisk/src/system.rs
> +impl SortedMembers<AccountId> for TechCommAccounts {
please use the tech committee storage for this

2024-01-30 10:20 UTC, mrq1911 commented on node/Cargo.toml
> +version = "11.0.1"
this is at least a minor bump

2024-02-26 12:20 UTC, jak-pan commented
Wait do we also need this on snek?

2024-02-26 12:32 UTC, Roznovjak commented
> Wait do we also need this on snek?

AFAIK we have the issue with PoV size on Basilisk as well.

2024-03-28 12:38 UTC, mrq1911 approved these changes

2024-03-28 18:31 UTC, merged