feat: update fee calculation
galacticcouncil/Basilisk-node pull request #66
Opened 2021-06-17 19:49 UTC by Roznovjak

## Description
Current fees for a TX are set too low. Tune the costs.

## Related Issue
Fixes: #52

2021-06-17 20:20 UTC, lumir-mrkva approved these changes

2021-06-17 20:26 UTC, lumir-mrkva requested changes
- [x] calculate price of transfer in USD
- [ ] decide final values

2021-06-22 08:57 UTC, Roznovjak commented
Transfer costs 0.006 $     (0.01 in kusama)
Full block: 393 $    (405 in kusama)
Fee multiplier after one hour of operation with fully loaded blocks: 1.0135      (the same as in kusama)
After one day: 1.3826      (the same as in kusama)

2021-06-28 11:25 UTC, jak-pan approved these changes
LGTM

2021-06-28 12:34 UTC, lumir-mrkva approved these changes

2021-06-28 12:58 UTC, merged