feat: async backing
galacticcouncil/Basilisk-node pull request #672
Opened 2024-10-02 11:05 UTC by vgantchev

2024-10-03 11:09 UTC, jak-pan commented on runtime/basilisk/src/lib.rs
I think we need the inherents. ( I saw somebody had problem with this )

2024-10-03 11:11 UTC, jak-pan commented on runtime/basilisk/src/lib.rs
But if we have it elsewhere then ok

2024-10-25 08:08 UTC, jak-pan commented on node/src/service.rs
> +		authoring_duration: Duration::from_millis(1500),
This doesn't mean execution time right? It's just how much time we have to propose a block

2024-10-25 08:09 UTC, jak-pan commented on runtime/basilisk/src/system.rs
> +	type ConsensusHook = ConsensusHook;
I believe this is where inherents are checked now?

2024-10-25 08:15 UTC, jak-pan approved these changes

2024-10-25 09:30 UTC, jak-pan commented on runtime/basilisk/src/lib.rs
I'll answer myself, it's in auraExt now

2024-10-25 09:30 UTC, jak-pan commented on runtime/basilisk/src/system.rs
> +	type ConsensusHook = ConsensusHook;
Yes...

2024-10-26 16:24 UTC, mrq1911 requested changes
ensure that session pallet doesnt break

2024-10-26 16:24 UTC, mrq1911 commented on primitives/src/constants.rs
> +		WEIGHT_REF_TIME_PER_SECOND.saturating_mul(2),
size of block (weight) is 4x what was before @jak-pan

2024-10-26 16:24 UTC, mrq1911 commented on runtime/basilisk/src/system.rs
> +	pub const RewardPerCollator: Balance = 15_240_000_000_000_000; // 6.35[BSX/block] * 2400[block]
should be 1/2 if the session length remain the same (1200 blocks)

2024-10-26 16:24 UTC, mrq1911 commented on primitives/src/constants.rs
>  	pub const HOURS: BlockNumber = MINUTES * 60;
session length uses this constant, and that shouldn't probably change as it would break conversion from block number to session

2024-10-28 17:46 UTC, mrq1911 approved these changes

2024-10-28 17:46 UTC, merged